### ISSUE TITLE
Reunión Starter / Kick Off

### ISSUE THREAD

**Issue by amalbala** [beerjs/jaen#1]
Buenas, 

¿Podemos quedar un día para vernos las caras los interesados? Algunos de [OlivaAgile](https://groups.google.com/forum/#!forum/olivagile) Vamos a ir al GDG Fest Dev, igual podemos quedar para conocernos o si no montar algo aparte.

Saludos.

**Comment by maxcosworth** [comment]
+1

**Comment by vrivas** [comment]
Gracias por el interés. Por desgracia, debido al horario del GDG de Jaén (creo que han llamado al evento Android Study Jam, ¿no?) es imposible para acceder.
Dejadme un poquito de tiempo para organizarme, por favor.  Pero vamos, que en la primera quincena de noviembre nos vemos a más tardar.

**Comment by smuriana** [comment]
Victor se refieren al Devfest, es un evento en el que participo y será el
Sábado 7 de noviembre en el IFEJA, puedes echarle un ojo en www.gdgjaen.xyz

Un saludo!

**Comment by vrivas** [comment]
Ah... eso ya es otra cosa. ¿a qué hora créeis que podríamos vernos? Porque
me imagino que estaréis liados con el propio devfest.

El 22 de octubre de 2015, 18:10, Sergio Muriana notifications@github.com
escribió:

> Victor se refieren al Devfest, es un evento en el que participo y será el
> Sábado 7 de noviembre en el IFEJA, puedes echarle un ojo en
> www.gdgjaen.xyz
> 
> Un saludo!
> El 22/10/2015 5:38 p. m., "Víctor Manuel Rivas Santos" <
> notifications@github.com> escribió:
> 
> > Gracias por el interés. Por desgracia, debido al horario del GDG de Jaén
> > (creo que han llamado al evento Android Study Jam, ¿no?) es imposible
> > para
> > acceder.
> > Dejadme un poquito de tiempo para organizarme, por favor. Pero vamos, que
> > en la primera quincena de noviembre nos vemos a más tardar.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/beerjs/jaen/issues/1#issuecomment-150265421.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/beerjs/jaen/issues/1#issuecomment-150273983.

## 

_Victor Manuel Rivas Santos_

**Comment by Joseja8** [comment]
Yo también me apunto! Sería una propuesta muy interesante, sin duda.

**Comment by AdPL** [comment]
¡Yo también me apunto!
@Joseja8 y yo estaremos también por el GDG Fest Dev.

**Comment by dmoyadev** [comment]
Yo por desgracia no podré asistir al DevFest, pero me interesa bastante la idea y espero que haya otra oportunidad pronto :D

**Comment by vrivas** [comment]
Si. Ya estoy viendo posibilidades de usar alguna estancia de la UJA... a
ver si escribo un par de correos o hago alguna llamada y nos dejan algún
sitio.

2015-10-22 22:23 GMT+02:00 Dani notifications@github.com:

> Yo por desgracia no podré asistir al DevFest, pero me interesa bastante la
> idea y espero que haya otra oportunidad pronto :D
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/beerjs/jaen/issues/1#issuecomment-150346122.

## 

_Victor Manuel Rivas Santos_

**Comment by vrivas** [comment]
Buenas de nuevo, @amalbala, @maxcosworth , @smuriana , @Joseja8 , @AdPL 
Al final no me habéis dicho a qué hora podríamos vernos el 7/Nov; por favor, es fundamental para mi, por temas de familia porque tengo que ver si puedo o no ir.
Si os parece, os propongo una alternativa: el jueves, 12 de noviembre, en alguna dependencia del edificio A3 que ya estoy gestionando, sobre las 19:30 o 20:00 horas... ¿qué me decís? Para mi desde luego sería mucho más fácil.
Espero opiniones

**Comment by dmoyadev** [comment]
Si fuese el día 12 yo sí podría asistir. ¡Voto a favor de la alternativa!

**Comment by smuriana** [comment]
Por mi no hay problema, cuantos más podamos juntarnos, mejor!

El 3 de noviembre de 2015, 12:19, Dani notifications@github.com escribió:

> Si fuese el día 12 yo sí podría asistir. ¡Voto a favor de la alternativa!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/beerjs/jaen/issues/1#issuecomment-153321210.

## 

Sergio Muriana.
Desarrollador web & Android

**Comment by Joseja8** [comment]
Por mi no hay problema, me viene perfecto!

**Comment by maxcosworth** [comment]
Yo el 12 estaré de viaje así que no contéis conmigo para ese día. Pero me sumo a la próxima.

/cc @pedrorevueltas @skuark (que igual les interesa)

**Comment by skuark** [comment]
Yo creo que podré sumarme también el día 12. Si no surge imprevisto por allí nos vemos :+1:

**Comment by AdPL** [comment]
Perfecto el día 12, sin problema.

**Comment by amalbala** [comment]
Apuntado el día 12.

**Comment by raulmoyareyes** [comment]
Yo el día 12 no estaré en Jaén, el 7 o ya volveré para navidad. Estoy muy interesado en compartir conocimientos de Javascript por lo que intentaré seguiros siempre que pueda, aunque sea desde la distancia.

**Comment by vrivas** [comment]
Vaya... siento que no podamos estar todos... pero se trata de darle la "patada inicial" y que empiece a rodar la cosa.
Quedamos por tanto el día 12, a las 19:30. Estaremos como máximo 1 hora, para no eternizarnos.  El sitio os lo digo en cuanto pueda, pero lo más seguro que sea algún seminario de la planta 1 del A3.
No olvidéis llevar algo de bebercio/comercio ;)

**Comment by JuanFra1990** [comment]
Yo el dia 12 tambien podre estar ;)

**Comment by vrivas** [comment]
Hola.
Aunque lo he puesto en el readme, quedamos a las 19:30 el jueves en el hall del A3... de ahí nos iremos a la sala que nos indiquen (a ver si se deciden desde "arriba"). 
Tened en cuenta que el aparcamiento va a estar inhabilitado buena parte de la tarde (incluyendo las 19:30) debido a una carrera solidaria; así que habrá que dejar el coche fuera.
Me llevaré un proyector por si queréis alguno presentar algo.
La idea de este primer encuentro es conocernos y contarnos qué hacemos cada uno. A partir de ahí podemos hablar de cómo podemos enfocar las futuras reuniones.
Saludos!!

**Comment by vrivas** [comment]
Muy rápido: el Vic. de Estudiantes nos autoriza a usar la dependencia A3-911 (en la planta -1, donde comemos alumnos y profesores) pero con la condición de que **no llevemos nada de alcohol**.
Asi que en esta primera reunión será menos "beer" que "js" y ya discutimos cómo lo organizamos en las próximas.

**Comment by criso123** [comment]
Vamos a tener que cambiar el nombre a waterjs jajaja

**Comment by vrivas** [comment]
XD
Ahí l'has dao!

El 11 de noviembre de 2015, 14:14, criso123 notifications@github.com
escribió:

> Vamos a tener que cambiar el nombre a waterjs jajaja
> El 11/11/2015 13:59, "Víctor Manuel Rivas Santos" <
> notifications@github.com>
> escribió:
> 
> > Muy rápido: el Vic. de Estudiantes nos autoriza a usar la dependencia
> > A3-911 (en la planta -1, donde comemos alumnos y profesores) pero con la
> > condición de que _no llevemos nada de alcohol_.
> > Asi que en esta primera reunión será menos "beer" que "js" y ya
> > discutimos
> > cómo lo organizamos en las próximas.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/beerjs/jaen/issues/1#issuecomment-155777768.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/beerjs/jaen/issues/1#issuecomment-155783173.

## 

_Victor Manuel Rivas Santos_

**Comment by skuark** [comment]
Siento no haber podido pasarme finalmente pero se me ha complicado la tarde, salgo ahora de la oficina :disappointed:

Espero que la quedada haya sido provechosa y que estéis pensando ya en organizar próximas actividades, a las que espero poder unirme.

Saludos.

**Comment by Jamargle** [comment]
Digo lo mismo que lo que ha dicho Jesús Manuel.
A ver si en la próxima me puedo pasar!

**Comment by amalbala** [comment]
Los jueves es lo que tiene, yo también fallé. En la próxima intentaré estar

**Comment by JuanFra1990** [comment]
Yo tampoco pude ir, pero me han comentado que ha sido muy interesante y esas pegatinas estan muy chulas ¡Yo quiero unaa! 😜 jeje Buena iniciativa ¿para cuando la proxima?
