### ISSUE TITLE
Temas a tratar en la próxima reunión para el 26/octubre/2016

### ISSUE THREAD

**Issue by vrivas** [beerjs/jaen#10]
Hola.
Perdonad la tardanza, pero los comienzos de curso siempre son complicados.
POr mi agenda de este año, las reuniones me vienen bien el miércoles por la noche, así que iba a poner la siguiente el día 19 de octubre...¡¡pero hay champions!! (Barcelona y Ath. Madrid) así que no quiero estropearos la juerga.
Si os parece, nos vemos el miércoles, **26 de octubre**, en el lugar de siempre (salvo que me digan lo contrario en el vicerrectorado), a las **19:45h.**
Sería interesante que propusieseis temas.
En Granada, un grupo de gente quiere montar un hackaton sobre [Electron](http://electron.atom.io/) que sinceramente no sé lo que es.
¿Qué opináis?

**Comment by dmoyadev** [comment]
A mí me gustaría hablar sobre la página web [Free Code Camp](https://www.freecodecamp.com/), cuyo propósito es el de ayudar a organizaciones no lucrativas a través de la enseñanza de lenguajes web (HTML, CSS y Javascript), que se me quedó pendiente de la anterior quedada. Es más para principiantes, pero es muy curiosa.

También, si hubiera tiempo, me gustaría comentar la página [CodeFights](https://codefights.com/home), que nos desafía en muchos lenguajes (entre ellos Javascript) con algunos retos bastante graciosetes. También tiene la opción de desafiar a amigos, empresas, y bots. Muy curioso todo 😛

**Comment by vrivas** [comment]
Genial, adjudicado.
Ese día empiezas tú ;)

**Comment by xtoxico** [comment]
Buenos días gente. muchas gracias por las charlas de ayer día 26 de octubre. Como ya se propuso ayer podríamos intentar quedar los últimos martes / miércoles de cada mes (dependiendo del fútbol, jejejee). Para tratar nuevos temas de este amplio mundillo al que nos enfrentamos como es el javascript. 

Yo puedo hablar en la próxima de lo fácil que es montar una aplicación multiplataforma (incluyendo MetroAPPs de windows 8.1 o Universal APP de windows 10) en apache cordova utilizando Intel XDK como IDE de desarrollo; de la utilización de IONIC2 como framework para el aspecto de las aplicaciones moviles;  de la utilización de librerias como RequireJS o Underscore. Hablar también un poquito de TypeScript

Propongo que alguien se prepare una charlita sobre las nuevas bondades de Angular2 JS por ejemplo... la cual sería bastante interesante. O incluso buscar un tema interesante para intentar desarrollar alguna aplicación común.

Si hay gente dentro del grupo que le gusten los videojuegos (tema que puede conseguir llamar a más gente), dar una introducción a COCOS2d.js.... incluso proponer hacer un remake de opensource de cualquier clásico en Javascript...

Estoy abierto a sugerencias

Un saludo a todos

**Comment by vrivas** [comment]
Bueno, como es costumbre, voy a cerrar este issue dando por concluida la reunión del 26, y abro una para el próximo día.
@xtoxico Muy interesate todo lo que propones, pero quizá sea demasiado para una sola sesión. Si te parece, empezamos con Intel XDK... bueno, lo pongo en el siguiente issue.
