### ISSUE TITLE
Cartel para promocionar los encuentros

### ISSUE THREAD

**Issue by vrivas** [beerjs/jaen#12]
Lo siento... lo mío no es el diseño gráfico :D
Tenéis el cartel en https://github.com/beerjs/jaen/blob/master/assets/cartel-encuentro.pdf (formato PDF) y https://github.com/beerjs/jaen/blob/master/assets/cartel-encuentro.odt (formato ODT de LibreOffice).
Tengo además unos cuantos impresos (los he dejado en la puerta de mi despacho, en un sobre de plástico). Podéis venir y cogerlos aunque yo no esté.
Saludos!

**Comment by dmoyadev** [comment]
He cogido esta mañana un par de ellos para colgarlos en la clase de 2º y 3º de Ingeniería Informática, a ver si se anima alguien más.

**Comment by vrivas** [comment]
Genial.
Gracias!!

**Comment by vrivas** [comment]
Parece que lo de los carteles ha funcionado... vinieron algunas personas nuevas gracias a ellos.
Por desgracia... ¡¡fueron los únicos que vinieron!! :'(
En fin... a ver si esto "despega".
