### ISSUE TITLE
Segunda quedada... fechas y posibles tareas

### ISSUE THREAD

**Issue by vrivas** [beerjs/jaen#2]
Estupendo, a juicio de todos, el resultado de nuestra primera reunión.
Siento que tengamos que seguir quedando los jueves, pero al menos para mi es el único día posible por ahora.
Hemos decidido juntarnos más o menos una vez al mes. La próxima será el **10 de diciembre**, un pelín más tarde, a las **19:45 horas**, y en el mismo sitio (**sala A3-911, en el sótano del A3**). Recordad que lo que llevemos de beber, ha de ser sin alcohol.
Hemos pensado que puede ser una buena idea aprovechar los encuentros para enseñarnos cosas (de Javascript, de Javascript :D ) unos a otros. No serán grandes cursos, sino pequeñas charlas de 5 o 10 minutos en las que poder aprender nuevos conceptos.
Si mal no recuerdo, @spawnsito nos hablará de Gulp en la próxima quedada. Yo intentaré dar un par de nociones sobre map, reduce, filter y foreach, si os parece bien. Y @adlp y @joseja8 nos contarán algo sobre Scala y, a ser posible, sobre Scala.js. No tiene por qué ser en este orden ;)

**Comment by cruzcivieta** [comment]
Día 12 o día 10?

**Comment by vrivas** [comment]
10!!! Día 10... ¡¡qué mayor que estoy!!

**Comment by vrivas** [comment]
Mi ejemplo para la charleta de mañana sobre map, reduce, etc: https://github.com/vrivas/map-reduce

**Comment by JuanFra1990** [comment]
Gran quedada con una muy buena explicación de Gulp de @spawnsito y explicación tortillera de @vrivas 😜  a investigar temas para la tercera quedada 😁😁

**Comment by vrivas** [comment]
A ver... tortillera porque iba sobre tortillas, no porque fuera mala, que conste :laughing:

**Comment by vrivas** [comment]
Por cerrar el issue:
Asistentes a la segunda quedada: @criso123, @spawnsito, @lynx901, @joseja8, @adpl, @vrivas y @juanfra1990
@vrivas habló de foreach, map, reduce y filter
@spawnsito nos enseñó cómo se utiliza gulp, junto con un montón de cosas chulas como browser-sync
Quedó pendiente la charla de @joseja8 sobre Scala
En principio, se baraja la fecha del 21-Enero-2016 para la próxima quedada.
