### ISSUE TITLE
Propuesta de "orden del día" para la reunión del 28/Enero

### ISSUE THREAD

**Issue by vrivas** [beerjs/jaen#4]
Una vez que parece claro que tenemos que posponer lo del proyecto de TDD, paso a proponer temas para la próxima reunión. Añadid, modificad, quitad lo que queráis.
- @adlp y @joseja8 nos podrían contar algo sobre Scala y, a ser posible, sobre Scala.js. No tiene por qué ser en este orden ;)
- @vrivas pueden contar algo sobre katas para TDD (o cualquier otra persona que se ofrezca)
- Podemos discutir entre todos hacia dónde queremos llevar esta pequeña comunidad de Javascript organizada en torno al beerjs
- A raíz del punto anterior, podemos proponer temas para la siguiente quedada así como una fecha. Por ejemplo, @spawnsito propuso hablar de patrones de diseño.

**Comment by vrivas** [comment]
Por favor, confirmadme que nos vemos el 21/Enero, o si preferís que la movamos a la semana siguiente, cuando ya no haya exámenes.
/cc @vrivas, Manuel Cano, M. Angeles Godino, @spawnsito, @joseja8, @adpl, @lynx901, Angel Luis, @criso123, @spawnsito, @lynx901, @joseja8, @adpl, @vrivas y @juanfra1990

**Comment by Joseja8** [comment]
Siento haber estado perdido este mes, pero los exámenes no perdonan!
Yo voto por pasarlo a la semana siguiente, cuando se estabilice situación (y las horas de sueño, también).

A ver que dicen los demás.

**Comment by cruzcivieta** [comment]
A mí me da igual que sea esta semana o la que viene. Saludos.

El 20 de enero de 2016, 12:48, José Rosell notifications@github.com
escribió:

> Siento haber estado perdido este mes, pero los exámenes no perdonan!
> Yo voto por pasarlo a la semana siguiente, cuando se estabilice situación
> (y las horas de sueño, también).
> 
> A ver que dicen los demás.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/beerjs/jaen/issues/4#issuecomment-173181382.

## 

_Daniel Cruz CivietaIngeniero Informático_

https://twitter.com/dcruzing
https://www.linkedin.com/profile/view?id=186634640

**Comment by vrivas** [comment]
OK. Pues por otro lado también me han llegado propuestas de cambiarlo, asi que mejor lo dejamos para la semana que viene.
Siento avisar tan tarde, pero es que también yo estoy al límite :/
