### ISSUE TITLE
Retomando las reuniones beerjs

### ISSUE THREAD

**Issue by vrivas** [beerjs/jaen#6]
Hola.
Perdonad el parón que hemos tenido, pero es que han sido un par de meses muy complicados.
¿Qué os parece si vamos proponiendo fechas? ¿Queréis que cambiemos los jueves por los lunes? Tendria que ser a partir de las 8 y media, que acabo las clases.
Espero propuestas,
Saludos!

**Comment by jotaeler** [comment]
¿A qué hora se venía haciendo el encuentro hasta ahora los jueves?

**Comment by vrivas** [comment]
Si mal no recuerdo, a las 19:45 aprox.
Yo puedo los jueves a partir de esa hora y también los lunes, a partir de
las 20:30.
Id diciendo los demás, a ver si podemos llegar a un acuerdo.

2016-03-31 15:56 GMT+02:00 jotaeler notifications@github.com:

> ¿A qué hora se venía haciendo el encuentro hasta ahora los jueves?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/beerjs/jaen/issues/6#issuecomment-203951979

## 

_Victor Manuel Rivas Santos_

**Comment by jotaeler** [comment]
¿A qué hora se venía haciendo el encuentro hasta ahora los jueves?

**Comment by jotaeler** [comment]
Yo personalmente preferiría un jueves

**Comment by ghost** [comment]
Buenas!

En realidad me enteré hace poco de esto. En realidad, me viene bien a cualquier hora, siendo por la tarde.

Eso si, si las reuniones se alargan más allá de las 9 debería saberlo, porque soy de pueblo y dependo del bus para volver xD

**Comment by vrivas** [comment]
Gracias por participar, Daniel.
El horario como ves aún está en el aire; pero el ambiente es totalmente
informal, así que no tengas problema en salir cuando veas que es la hora de
coger el autobús.
Hasta ahora, las reuniones de los jueves, estábamos acabando antes de las
9, pero era porque empezábamos sobre las 19:45. A ver cómo queda finalmente
la próxima convocatoria.

El 31 de marzo de 2016, 17:19, Daniel Trujillo Viedma <
notifications@github.com> escribió:

> Buenas!
> 
> En realidad me enteré hace poco de esto. En realidad, me viene bien a
> cualquier hora, siendo por la tarde.
> 
> Eso si, si las reuniones se alargan más allá de las 9 debería saberlo,
> porque soy de pueblo y dependo del bus para volver xD
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/beerjs/jaen/issues/6#issuecomment-203983671

## 

_Victor Manuel Rivas Santos_

**Comment by JuanFra1990** [comment]
Buenas gente

Yo sabiendolo con tiempo los jueves salgo a las 20 de la academia, me seria dificil llegar a la hora pero yo lo veo bien, los jueves.

**Comment by vrivas** [comment]
Bien. Para no demorarlo mucho más y no meternos en época de exámenes, si os parece quedamos el Jueves, 5/Mayo a las 20:30. Antes para mi es imposible porque tengo clase.
Voy a cerrar este issue y abrir uno específico para esa fecha; para ver quiénes venimos y de qué hablamos.
