### ISSUE TITLE
Temas para la próxima reunión / Topics for next meeting:  5-May-2016, 20:30h

### ISSUE THREAD

**Issue by vrivas** [beerjs/jaen#7]
Abrimos el issue para ver de qué hablamos en la próxima reunión.
Me gustaría que viniese gente de 1º que aún no tiene mucho contacto con Javascript, así que yo puedo dar un breve taller sobre Javascript o jQuery.

**Comment by ghost** [comment]
Me encantaría que se hablase de Javascript, porque sé muy poco sobre él.

Yo este fin de semana he programado un bot de telegram muy sencillo, si os parece interesante podría hablar un poco de él y si suscita interés preparar un taller más formal.

**Comment by vrivas** [comment]
Lo del bot me parece genial, Daniel.
Elige tú el formato q quieras para presentarlo.
Si crees q se puede hacer otro día un taller abierto a todo el mundo,
hablamos ese día de cómo organizarlo.

El miércoles, 13 de abril de 2016, Daniel Trujillo Viedma <
notifications@github.com> escribió:

> Me encantaría que se hablase de Javascript, porque sé muy poco sobre él.
> 
> Yo este fin de semana he programado un bot de telegram muy sencillo, si os
> parece interesante podría hablar un poco de él y si suscita interés
> preparar un taller más formal.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/beerjs/jaen/issues/7#issuecomment-209550567

## 

_Victor Manuel Rivas Santos_

**Comment by vrivas** [comment]
Genial la respuesta a la reunión del 5-5-2016.
Muy interesante lo que nos contó Daniel (@gdabi) sobre los bot para Telegram (puedes ver el código en https://github.com/gdabi/TAUJABot).

Nos quedamos con ganas de que @lynx901 nos enseñara unos cuantos recursos donde aprender JavaScript... así que abre él con este tema la próxima reunión ;)

Finalmente, dejo los enlaces a un par de fotos que están en la carpeta de imágenes:
- https://github.com/beerjs/jaen/blob/master/images/IMG_20160505_204735.jpg
- https://github.com/beerjs/jaen/blob/master/images/IMG_20160505_211927.jpg
