### ISSUE TITLE
Que se nos pasan los meses!!! ¿próximo encuentro?

### ISSUE THREAD

**Issue by vrivas** [beerjs/jaen#8]
Hola.
Se pasan los días que ni nos damos cuenta... 
¿Próximo encuentro?
Para mi imposible la primera semana de junio.
¿Os parece bien el 13 de junio? Hasta la semana siguiente no empiezan los exámenes.
También tendríamos que empezar a ver qué temas vamos a tratar.

**Comment by vrivas** [comment]
Por cierto, que debería funcionar la integración con el canal #jaen del grupo beerjs en Slack

**Comment by vrivas** [comment]
Ahora funciona.
Si os suscribís al grupo: beerjs en slack, podéis ver todos los mensajes que creamos en estos issues añadiéndoos al canal #jaen dentro de dicho grupo.
Si me decís vuestro correo, posiblemente pueda añadiros yo.

**Comment by jotaeler** [comment]
Hola! al final será el día 13 de junio el próximo evento??

**Comment by vrivas** [comment]
Pues si, tendrá que ser el 13 de junio. Ahora mismo lo publicito.
Lo que vamos a hacer es ponerlo más temprano, así tenemos más tiempo. 
19:30, ok?
